

import pygame

# About position values in pygame
# -> https://stackoverflow.com/questions/62804292/how-to-set-the-position-of-an-image-in-pygame

class Celebration(pygame.sprite.Sprite):
    def __init__(self, name, kestitsija, fontsize):

        self.pirskeiden_pitaja = kestitsija

        self.my_font = pygame.font.SysFont('Comic Sans MS', fontsize)

        self.name = name
        # 1 apina
        # 2 kg perunoita
        # 3 dl kuohukermaa
        # 2 tl mustapippuria
        # 1 tl suolaa

    def laskelmat(self):
        self.selvinneet_apinat = self.pirskeiden_pitaja.apinat_perilla
        self.ruokitut_suut = self.selvinneet_apinat * 4
        self.pippuria_kaytetty_tl = self.selvinneet_apinat*2


    def draw(self, screen):
        self.laskelmat()

        #  text boxes generated by chatgpt

        # Render the text
        self.text_surface1 = self.my_font.render(f"{self.name} juhlissa suita ruokittu: {self.ruokitut_suut}", False, (255, 0, 0))
        self.text_surface2 = self.my_font.render(f"Pippuria käytetty: {self.pippuria_kaytetty_tl} tl", False, (255,0,0))

        # Get the width and height of the text surfaces
        text_rect1 = self.text_surface1.get_rect()
        text_rect2 = self.text_surface2.get_rect()

        # Set positions for the text
        text_rect1.topleft = (self.pirskeiden_pitaja.rect.x-100, self.pirskeiden_pitaja.rect.y)
        text_rect2.topleft = (self.pirskeiden_pitaja.rect.x-100, self.pirskeiden_pitaja.rect.y+28)

        # Draw black rectangles behind the text
        pygame.draw.rect(screen, (0, 0, 0), text_rect1)
        pygame.draw.rect(screen, (0, 0, 0), text_rect2)

        # Blit the text on top of the black rectangles
        screen.blit(self.text_surface1, text_rect1.topleft)
        screen.blit(self.text_surface2, text_rect2.topleft)



    

    